version: "3.0"

services:
  #adpsampleapp:
  #  image: abpsampleapp
  #  ports:
  #    - "4200:4200"
  #    - "44357:44357"
  #  networks:
  #    - Abp-network
  #  depends_on:
  #    - mysql

  mysql:
    image: mysql:5.7
    volumes:
      - mysql-data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: AccessManagementDB
      MYSQL_USER: sa
      MYSQL_PASSWORD: 1234
    ports:
      - 3306:3306
    networks:
      - Abp-network
    

networks:
  Abp-network:
    #name: my-network
    external: true

volumes:
  mysql-data:

  

